src/Isotope/Bundle/DbBundle/Entity/InternalDisposal.php
<?php

namespace Isotope\Bundle\DbBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * InternalDisposal
 *
 * @ORM\Table(name="internal_disposal")
 * @ORM\Entity(repositoryClass="Isotope\Bundle\DbBundle\Repository\InternalDisposalRepository")
 * @ORM\HasLifecycleCallbacks
 */
class InternalDisposal
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Category")
     * @see Category
     */
    private $category;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="fillingStart", type="date", nullable=true)
     */
    private $fillingStart;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="fillingEnd", type="date", nullable=true)
     */
    private $fillingEnd;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetime", nullable=true)
     */
    private $date;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="actualDisposal", type="datetime", nullable=true)
     */
    private $actualDisposal;

    /**
     *
     * @ORM\ManyToOne(targetEntity="Barrel")
     * @see Barrel
     */
    private $barrelCategory;

    /**
     * @var string
     *
     * @ORM\Column(name="barrelNumber", type="string", length=16, nullable=true)
     */
    private $barrelNumber;

    /**
     * @var float
     *
     * @ORM\Column(name="barrelPackageWeight", type="float", nullable=true)
     */
    private $barrelPackageWeight;

    /**
     * @var float
     *
     * @ORM\Column(name="totalWeight", type="float", nullable=true)
     */
    private $totalWeight;

    /**
     * @var float
     *
     * @ORM\Column(name="amount", type="float", nullable=true)
     */
    private $amount;

    /**
     * @var string
     *
     * @ORM\Column(name="comment", type="text", nullable=true)
     */
    private $comment;

   /**
     * @ORM\PostLoad
     * @ORM\PrePersist
     */
    public function getCalculatedDisposalDate()
    {
        if($this->category != null && $this->totalWeight != $this->barrelPackageWeight &&
                $this->category->getReleaseLimit() > 0) {

            $desay_days = $this->getDaysBeforeReleaseCount();

            $calculatedDate = new \DateTime();
            $calculatedDate->setTimestamp(strtotime($this->date->format('Y-m-d')));
            $calculatedDate->modify('+'.intval($desay_days).' days');
            return  $calculatedDate;
        } else {
            return null;
        }
    }

    public function getDropWeight()
    {
        return ($this->totalWeight-$this->barrelPackageWeight) * 1000;
    }

    public function getSpecActivity()
    {
        return $this->amount / $this->getDropWeight();
    }

    public function getStatus()
    {
        if($this->actualDisposal === null) {
            return 'Actual';
        }
        return 'Approved';
    }

    public function getDaysBeforeReleaseCount()
    {
        return (log($this->getSpecActivity() / $this->category->getReleaseLimit()) * $this->getCategory()->getHalfLife()) / 0.6931471806;
    }

    /**
     * Get string name
     *
     * @return string
     */
    public function __toString()
    {
        if ($this->getId())
            return "Interne Entsorgung ".$this->getId();
        return "Neue Interne Entsorgung";
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set fillingStart
     *
     * @param \DateTime $fillingStart
     * @return InternalDisposal
     */
    public function setFillingStart($fillingStart)
    {
        $this->fillingStart = $fillingStart;
    
        return $this;
    }

    /**
     * Get fillingStart
     *
     * @return \DateTime 
     */
    public function getFillingStart()
    {
        return $this->fillingStart;
    }

    /**
     * Set fillingEnd
     *
     * @param \DateTime $fillingEnd
     * @return InternalDisposal
     */
    public function setFillingEnd($fillingEnd)
    {
        $this->fillingEnd = $fillingEnd;
    
        return $this;
    }

    /**
     * Get fillingEnd
     *
     * @return \DateTime 
     */
    public function getFillingEnd()
    {
        return $this->fillingEnd;
    }

    /**
     * Set barrelNumber
     *
     * @param string $barrelNumber
     * @return InternalDisposal
     */
    public function setBarrelNumber($barrelNumber)
    {
        $this->barrelNumber = $barrelNumber;
    
        return $this;
    }

    /**
     * Get barrelNumber
     *
     * @return string 
     */
    public function getBarrelNumber()
    {
        return $this->barrelNumber;
    }

    /**
     * Set barrelPackageWeight
     *
     * @param float $barrelPackageWeight
     * @return InternalDisposal
     */
    public function setBarrelPackageWeight($barrelPackageWeight)
    {
        $this->barrelPackageWeight = $barrelPackageWeight;
    
        return $this;
    }

    /**
     * Get barrelPackageWeight
     *
     * @return float 
     */
    public function getBarrelPackageWeight()
    {
        return $this->barrelPackageWeight;
    }

    /**
     * Set totalWeight
     *
     * @param float $totalWeight
     * @return InternalDisposal
     */
    public function setTotalWeight($totalWeight)
    {
        $this->totalWeight = $totalWeight;
    
        return $this;
    }

    /**
     * Get totalWeight
     *
     * @return float 
     */
    public function getTotalWeight()
    {
        return $this->totalWeight;
    }

    /**
     * Set amount
     *
     * @param float $amount
     * @return InternalDisposal
     */
    public function setAmount($amount)
    {
        $this->amount = $amount;
    
        return $this;
    }

    /**
     * Get amount
     *
     * @return float 
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Set comment
     *
     * @param string $comment
     * @return InternalDisposal
     */
    public function setComment($comment)
    {
        $this->comment = $comment;
    
        return $this;
    }

    /**
     * Get comment
     *
     * @return string 
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Set category
     *
     * @param \Isotope\Bundle\DbBundle\Entity\Category $category
     * @return InternalDisposal
     */
    public function setCategory(\Isotope\Bundle\DbBundle\Entity\Category $category = null)
    {
        $this->category = $category;
    
        return $this;
    }

    /**
     * Get category
     *
     * @return \Isotope\Bundle\DbBundle\Entity\Category 
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Set barrelCategory
     *
     * @param \Isotope\Bundle\DbBundle\Entity\Barrel $barrelCategory
     * @return InternalDisposal
     */
    public function setBarrelCategory(\Isotope\Bundle\DbBundle\Entity\Barrel $barrelCategory = null)
    {
        $this->barrelCategory = $barrelCategory;
    
        return $this;
    }

    /**
     * Get barrelCategory
     *
     * @return \Isotope\Bundle\DbBundle\Entity\Barrel 
     */
    public function getBarrelCategory()
    {
        return $this->barrelCategory;
    }

    public function getBarrelLabel()
    {
        $lbl = "{$this->barrelCategory} #{$this->barrelNumber}"; 
        if ($this->barrelCategory->getDescription() !== '') {
            $lbl .= " - {$this->barrelCategory->getDescription()}";
        }

        return $lbl;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return InternalDisposal
     */
    public function setDate($date)
    {
        $this->date = $date;
    
        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime 
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set actualDisposal
     *
     * @param \DateTime $actualDisposal
     * @return InternalDisposal
     */
    public function setActualDisposal($actualDisposal)
    {
        $this->actualDisposal = $actualDisposal;
    
        return $this;
    }

    /**
     * Get actualDisposal
     *
     * @return \DateTime 
     */
    public function getActualDisposal()
    {
        return $this->actualDisposal;
    }

    /**
     * Get amount in uCi
     *
     * @return float
     */
    public function getAmountUci()
    {
        return $this->amount / 37000;
    }

    /**
     * Set amount in uCi
     *
     * @param float $amount
     * @return Order
     */
    public function setAmountUci($amount)
    {
        $this->amount = $amount * 37000;
    
        return $this;
    }
}

src/Isotope/Bundle/DbBundle/Entity/Isotope.php
<?php

namespace Isotope\Bundle\DbBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Isotope
 *
 * @ORM\Table(name="isotope")
 * @ORM\Entity
 */
class Isotope
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * 
     * @ORM\ManyToOne(targetEntity="Category")
     * @see Category
     */
    private $category;

    /**
     * @var string
     *
     * @ORM\Column(name="catalogNumber", type="string", length=15, nullable=true)
     */
    private $catalogNumber;

    /**
     * @var float
     *
     * @ORM\Column(name="rounding", type="float", nullable=true)
     */
    private $rounding;

    /**
     * @var float
     *
     * @ORM\Column(name="highestAmount", type="float", nullable=true)
     */
    private $highestAmount;

    /**
     * @var string
     *
     * @ORM\Column(name="company", type="string", length=255, nullable=true)
     */
    private $company;

    /**
     * @var string
     *
     * @ORM\Column(name="productLine", type="string", length=255, nullable=true)
     */
    private $productLine;

    /**
     * @var string
     *
     * @ORM\Column(name="substance", type="string", length=255, nullable=true)
     */
    private $substance;

    /**
     * @var string
     *
     * @ORM\Column(name="specificActivity", type="string", length=255, nullable=true)
     */
    private $specificActivity;

    /**
     * @var string
     *
     * @ORM\Column(name="concentration", type="string", length=255, nullable=true)
     */
    private $concentration;

    /**
     * @var string
     *
     * @ORM\Column(name="deliveryType", type="string", length=255, nullable=true)
     */
    private $deliveryType;

    /**
     * @var string
     *
     * @ORM\Column(name="note", type="text", nullable=true)
     */
    private $note;

    /**
     * @var boolean
     *
     * @ORM\Column(name="active ", type="boolean")
     */
    private $active = true;

    /**
     * Get string name
     *
     * @return string
     */
    public function __toString()
    {
        if ($this->getId())
            return $this->getWideName();
        return "Isotop hinzufügen";
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set catalogNumber
     *
     * @param string $catalogNumber
     * @return Isotope
     */
    public function setCatalogNumber($catalogNumber)
    {
        $this->catalogNumber = $catalogNumber;
    
        return $this;
    }

    /**
     * Get catalogNumber
     *
     * @return string 
     */
    public function getCatalogNumber()
    {
        return $this->catalogNumber;
    }

    /**
     * Set rounding
     *
     * @param integer $rounding
     * @return Isotope
     */
    public function setRounding($rounding)
    {
        $this->rounding = $rounding;
    
        return $this;
    }

    /**
     * Get rounding
     *
     * @return integer 
     */
    public function getRounding()
    {
        return $this->rounding;
    }

    /**
     * Set highestAmount
     *
     * @param integer $highestAmount
     * @return Isotope
     */
    public function setHighestAmount($highestAmount)
    {
        $this->highestAmount = $highestAmount;
    
        return $this;
    }

    /**
     * Get highestAmount
     *
     * @return integer 
     */
    public function getHighestAmount()
    {
        return $this->highestAmount;
    }

    /**
     * Set company
     *
     * @param string $company
     * @return Isotope
     */
    public function setCompany($company)
    {
        $this->company = $company;
    
        return $this;
    }

    /**
     * Get company
     *
     * @return string 
     */
    public function getCompany()
    {
        return $this->company;
    }

    /**
     * Set productLine
     *
     * @param string $productLine
     * @return Isotope
     */
    public function setProductLine($productLine)
    {
        $this->productLine = $productLine;
    
        return $this;
    }

    /**
     * Get productLine
     *
     * @return string 
     */
    public function getProductLine()
    {
        return $this->productLine;
    }

    /**
     * Set substance
     *
     * @param string $substance
     * @return Isotope
     */
    public function setSubstance($substance)
    {
        $this->substance = $substance;
    
        return $this;
    }

    /**
     * Get substance
     *
     * @return string 
     */
    public function getSubstance()
    {
        return $this->substance;
    }

    /**
     * Set specificActivity
     *
     * @param string $specificActivity
     * @return Isotope
     */
    public function setSpecificActivity($specificActivity)
    {
        $this->specificActivity = $specificActivity;
    
        return $this;
    }

    /**
     * Get specificActivity
     *
     * @return string 
     */
    public function getSpecificActivity()
    {
        return $this->specificActivity;
    }

    /**
     * Set concentration
     *
     * @param string $concentration
     * @return Isotope
     */
    public function setConcentration($concentration)
    {
        $this->concentration = $concentration;
    
        return $this;
    }

    /**
     * Get concentration
     *
     * @return string 
     */
    public function getConcentration()
    {
        return $this->concentration;
    }

    /**
     * Set deliveryType
     *
     * @param string $deliveryType
     * @return Isotope
     */
    public function setDeliveryType($deliveryType)
    {
        $this->deliveryType = $deliveryType;
    
        return $this;
    }

    /**
     * Get deliveryType
     *
     * @return string 
     */
    public function getDeliveryType()
    {
        return $this->deliveryType;
    }

    /**
     * Set note
     *
     * @param string $note
     * @return Isotope
     */
    public function setNote($note)
    {
        $this->note = $note;
    
        return $this;
    }

    /**
     * Get note
     *
     * @return string 
     */
    public function getNote()
    {
        return $this->note;
    }

    /**
     * Set category
     *
     * @param \Isotope\Bundle\DbBundle\Entity\Category $category
     * @return Isotope
     */
    public function setCategory(\Isotope\Bundle\DbBundle\Entity\Category $category = null)
    {
        $this->category = $category;
    
        return $this;
    }

    /**
     * Get category
     *
     * @return \Isotope\Bundle\DbBundle\Entity\Category 
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Set active
     *
     * @param boolean $active
     * @return Isotope
     */
    public function setActive($active)
    {
        $this->active = $active;
    
        return $this;
    }

    /**
     * Get active
     *
     * @return boolean 
     */
    public function getActive()
    {
        return $this->active;
    }
    
    /**
     * Get long description
     *
     * @return string 
     */
    public function getWideName() {
        return $this->productLine.' '.$this->substance.' '.
            $this->specificActivity.' '.$this->concentration.' [Nr.: '.
            $this->catalogNumber.']';
    }
    
    /**
     * Get long description for weekly report
     *
     * @return string 
     */
    public function getWideNameWeekly() {
        return $this->productLine.' '.$this->substance.', '.
            $this->specificActivity.', '.$this->concentration.' ('.
            $this->category->getName().')';
    }

    /**
     * Get highest amount in uCi
     *
     * @return float
     */
    public function getHighestAmountUci()
    {
        return $this->highestAmount / 37000;
    }
}

src/Isotope/Bundle/DbBundle/Resources/views/Admin/hide.html.twig
{% extends 'SonataAdminBundle:CRUD:delete.html.twig' %}

{% block content %}
    <div class="sonata-ba-delete">

        <h1>{{ 'title_hide'|trans() }}</h1>

        {{ 'message_hide_confirmation'|trans() }}

        <div class="well well-small form-actions">
            <form method="POST" action="{{ admin.generateObjectUrl('hide', object) }}">
                <input type="hidden" name="_method" value="DELETE" />
                <input type="hidden" name="_sonata_csrf_token" value="{{ csrf_token }}" />

                <button type="submit" class="btn btn-danger"><i class="icon-trash icon-white"></i> {{ 'btn_hide'|trans() }}</button>
                {% if admin.hasRoute('edit') and admin.isGranted('EDIT', object) %}
                    {{ 'delete_or'|trans({}, 'SonataAdminBundle') }}

                    <a class="btn btn-success" href="{{ admin.generateObjectUrl('edit', object) }}">
                        <i class="icon-white icon-edit"></i>
                        {{ 'link_action_edit'|trans({}, 'SonataAdminBundle') }}</a>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}

src/Isotope/Bundle/DbBundle/Resources/views/Admin/hide__action_isotope.html.twig
{% if object.getActive == true %}
<a href="{{ admin.generateObjectUrl('hide', object) }}" class="btn delete_link btn-small" title="{{ 'action_delete'|trans({}, 'SonataAdminBundle') }}">
    <i class="icon-remove"></i>
    {{ 'deactivate_label' |trans() }}
</a>
{% else %}
<a href="{{ admin.generateObjectUrl('reactivate', object) }}" class="btn delete_link btn-small" title="{{ 'action_delete'|trans({}, 'SonataAdminBundle') }}">
{#    <i class="icon-remove"></i>#}
    {{ 'reactivate_label' |trans() }}
</a>
{% endif %}

src/Isotope/Bundle/DbBundle/Resources/views/Admin/list_full_isotope.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}


{% block field%}
    <div>
        <a href="javascript:void(0);" class="btn view_link btn-small show-isotope-btn" title="Anzeigen" data-isotope-id="{{ object.id }}" data-toggle="modal" data-target="#full_object_{{ object.id }}">
            <i class="icon-zoom-in"></i>
            Anzeigen
        </a>

        <div class="modal hide fade" id="full_object_{{ object.id }}">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Modal header</h3>
            </div>
            <div class="modal-body">

                <div class="sonata-ba-show">    <div class="sonata-ba-view">
                        <table class="table table-bordered">
                            <tbody><tr class="sonata-ba-view-title">
                                <td colspan="2">
                                    Isotope
                                </td>
                            </tr>

                            <tr class="sonata-ba-view-container">

                                <th>Category</th>
                                <td>{{ object.category.name }}
                                </td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Catalog Number</th>
                                <td>{{  object.catalogNumber }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Rounding</th>
                                <td>{{ object.rounding | science_number_format() }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Highest Amount</th>
                                <td>{{ object.highestAmount | science_number_format() }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Company</th>
                                <td>{{ object.company }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Product Line</th>
                                <td>{{ object.productLine }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Substance</th>
                                <td>{{ object.substance }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Specific Activity</th>
                                <td>{{ object.specificActivity }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Concentration</th>
                                <td>{{ object.concentration }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Delivery Type</th>
                                <td>{{ object.deliveryType }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Note</th>
                                <td>{{ object.note }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Active</th>
                                <td>
                                    {% spaceless %}
                                        {% if object.active %}
                                            <i class="icon-ok-circle"></i>
                                            {%- trans from 'SonataAdminBundle' %}label_type_yes{% endtrans -%}
                                        {% else %}
                                            <i class="icon-ban-circle"></i>
                                            {%- trans from 'SonataAdminBundle' %}label_type_no{% endtrans -%}
                                        {% endif %}
                                    {% endspaceless %}

                                </td>
                            </tr>
                            </tbody></table>
                    </div>
                </div>




            </div>
            <div class="modal-footer">
                <a href="#" class="btn"  data-dismiss="modal" aria-hidden="true">Schließen</a>
            </div>
        </div>
    </div>


{% endblock %}

src/Isotope/Bundle/DbBundle/Resources/views/Admin/list_full_isotope_order.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}


{% block field%}
    <div>
        <a href="javascript:void(0);" data-isotope-id="{{ object.isotope.id }}" data-toggle="modal" data-target="#full_object_{{ object.isotope.id }}">
            {{ object.isotope.wideName }}
        </a>

        <div class="modal hide fade" id="full_object_{{ object.isotope.id }}">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>&nbsp;</h3>
            </div>
            <div class="modal-body">

                <div class="sonata-ba-show">    <div class="sonata-ba-view">
                        <table class="table table-bordered">
                            <tbody><tr class="sonata-ba-view-title">
                                <td colspan="2">
                                    Isotope
                                </td>
                            </tr>

                            <tr class="sonata-ba-view-container">

                                <th>Kategorie</th>
                                <td>{{ object.isotope.category.name }}
                                </td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Katalog Nummer</th>
                                <td>{{  object.isotope.catalogNumber }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Rundung</th>
                                <td>{{ object.isotope.rounding | science_number_format() }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Höchste Menge</th>
                                <td>{{ object.isotope.highestAmount | science_number_format() }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Firma</th>
                                <td>{{ object.isotope.company }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Produktlinie</th>
                                <td>{{ object.isotope.productLine }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Substanz</th>
                                <td>{{ object.isotope.substance }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Spezifische Aktivität</th>
                                <td>{{ object.isotope.specificActivity }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Konzentration</th>
                                <td>{{ object.isotope.concentration }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Lieferart</th>
                                <td>{{ object.isotope.deliveryType }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Notiz</th>
                                <td>{{ object.isotope.note }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>Active</th>
                                <td>
                                    {% spaceless %}
                                        {% if object.isotope.active %}
                                            <i class="icon-ok-circle"></i>
                                            {%- trans from 'SonataAdminBundle' %}label_type_yes{% endtrans -%}
                                        {% else %}
                                            <i class="icon-ban-circle"></i>
                                            {%- trans from 'SonataAdminBundle' %}label_type_no{% endtrans -%}
                                        {% endif %}
                                    {% endspaceless %}

                                </td>
                            </tr>
                            </tbody></table>
                    </div>
                </div>




            </div>
            <div class="modal-footer">
                <a href="#" class="btn"  data-dismiss="modal" aria-hidden="true">Schließen</a>
            </div>
        </div>
    </div>


{% endblock %}

src/Isotope/Bundle/DbBundle/Resources/views/Admin/list_order_status_trans.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field%}

        <div>{{ object.status | trans() }}</div>



{% endblock %}

src/Isotope/Bundle/DbBundle/Resources/views/Admin/show__action_order_mci.html.twig
    <div style="display:inline">
        <a href="javascript:void(0);" class="btn view_link btn-small show-isotope-btn" title="Anzeigen" data-order-id="{{ object.id }}" data-toggle="modal" data-target="#full_order_{{ object.id }}">
            <i class="icon-zoom-in"></i>
            {{ 'show' |trans() }}
        </a>

        <div class="modal hide fade" id="full_order_{{ object.id }}">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>{{ 'order' |trans() }}</h3>
            </div>
            <div class="modal-body">

                <div class="sonata-ba-show">    <div class="sonata-ba-view">
                        <table class="table table-bordered order_show">
                            <tbody>

                            <tr class="sonata-ba-view-container">

                                <th>{{ 'show.label_date' |trans() }}</th>
                                <td>{{ object.date|date("d.m.Y") }}
                                </td>
                            </tr>
                            {%if object.stockDate is not null %}
                            <tr class="sonata-ba-view-container">

                                <th>{{ 'show.label_stock_date' |trans() }}</th>
                                <td>{{ object.date|date("d.m.Y") }}
                                </td>
                            </tr>
                            {%endif%}
                            <tr class="sonata-ba-view-container">
                                <th>{{ 'show.label_isotope' |trans() }}</th>
                                <td>{{  object.isotope }}</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>{{ 'show.label_amount' |trans() }}</th>
                                <td>{{ object.amount | science_number_format() }}&nbsp;
                                    ({{ object.getAmountUci | science_number_format() }})</td>
                            </tr>
                            <tr class="sonata-ba-view-container">
                                <th>{{ 'show.label_status_label' |trans() }}</th>
                                <td>{{ object.status }}</td>
                            </tr>
                            {%if object.disposed > 0 %}
                            <tr class="sonata-ba-view-container">
                                <th>{{ 'show.label_disposed' |trans() }}</th>
                                <td>{{ object.disposed }}</td>
                            </tr>
                            {%endif%}
                            <tr class="sonata-ba-view-container">
                                <th>{{ 'show.label_cost_center' |trans() }}</th>
                                <td>{{ object.costCenter }}</td>
                            </tr>

                            </tbody></table>
                    </div>
                </div>




            </div>
            <div class="modal-footer">
                <a href="#" class="btn"  data-dismiss="modal" aria-hidden="true">{{ 'close_label' |trans() }}</a>
            </div>
        </div>
    </div>