src/Isotope/Bundle/DbBundle/Entity/Order.php
<?php namespace Isotope\Bundle\DbBundle\Entity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Order
 *
 * @ORM\Table(name="`order`")
 * @ORM\Entity(repositoryClass="Isotope\Bundle\DbBundle\Repository\OrderRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Order
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     * @see User
     */
    private $user;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="date")
     *
     */
    private $date;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="stock_date", type="date", nullable=true)
     *
     */
    private $stockDate;

    /**
     * @ORM\ManyToOne(targetEntity="Isotope")
     * @ORM\JoinColumn(name="isotope_id", referencedColumnName="id")
     * @see Isotope
     */
    private $isotope;

    /**
     * @var float
     *
     * @ORM\Column(name="amount", type="float")
     */
    private $amount;


    /**
     * @var float
     *
     * @ORM\Column(name="disposed", type="float")
     */
    private $disposed = 0;

    /**
     * @var string
     *
     * @ORM\Column(name="status", type="status", nullable=true, options={"default" : "order"})
     */
    private $status;

    /**
     * @var string
     *
     * @ORM\Column(name="costCenter", type="string", length=255, nullable=true)
     */
    private $costCenter;

    /**
     * @var boolean
     *
     * @ORM\Column(name="visible", type="boolean", options={"default" : true})
     */
    private $visible = true;

    /**
     * Get string name
     *
     * @return string
     */
    public function __toString()
    {
        if ($this->getId()) {
            $label = $this->status;
 
            return "$label ".$this->getId();
        }
        return 'new order';
    }

    public function __construct()
    {
        if($this->date == null){
            $this->date = new \DateTime('now');
        }
        if($this->status == null){
            $this->status = 'order';
        }
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return Order
     */
    public function setDate($date = null)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime 
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set amount
     *
     * @param float $amount
     * @return Order
     */
    public function setAmount($amount)
    {
        $this->amount = $amount;
    
        return $this;
    }

    /**
     * Get amount
     *
     * @return float 
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Set status
     *
     * @param status $status
     * @return Order
     */
    public function setStatus($status)
    {
        $this->status = $status;
    
        return $this;
    }

    /**
     * Get status
     *
     * @return status 
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set costCenter
     *
     * @param string $costCenter
     * @return Order
     */
    public function setCostCenter($costCenter)
    {
        $this->costCenter = $costCenter;
    
        return $this;
    }

    /**
     * Get costCenter
     *
     * @return string 
     */
    public function getCostCenter()
    {
        return $this->costCenter;
    }

    /**
     * Set user
     *
     * @param \Isotope\Bundle\DbBundle\Entity\User $user
     * @return Order
     */
    public function setUser(\Isotope\Bundle\DbBundle\Entity\User $user = null)
    {
        $this->user = $user;
    
        return $this;
    }

    /**
     * Get user
     *
     * @return \Isotope\Bundle\DbBundle\Entity\User 
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set isotope
     *
     * @param \Isotope\Bundle\DbBundle\Entity\Isotope $isotope
     * @return Order
     */
    public function setIsotope(\Isotope\Bundle\DbBundle\Entity\Isotope $isotope = null)
    {
        $this->isotope = $isotope;
    
        return $this;
    }

    /**
     * Get isotope
     *
     * @return \Isotope\Bundle\DbBundle\Entity\Isotope 
     */
    public function getIsotope()
    {
        return $this->isotope;
    }

    /**
     * Set visible
     *
     * @param boolean $visible
     * @return Order
     */
    public function setVisible($visible)
    {
        $this->visible = $visible;
    
        return $this;
    }

    /**
     * Get visible
     *
     * @return boolean 
     */
    public function getVisible()
    {
        return $this->visible;
    }

    /**
     * Set disposed
     *
     * @param float $disposed
     * @return Order
     */
    public function addDisposed($disposed)
    {
        if ($this->getAmountLeft() < $disposed) {
            $disposed = $this->getAmountLeft();
        }

        if ($this->getAmountLeft() == $disposed) {
            $this->visible = false;
        }

        $this->disposed += $disposed;
    
        return $this;
    }

    public function delDisposed($disposed)
    {

        $left = 0;

        if ($this->disposed < $disposed) {
            $left = $disposed - $this->disposed;
            $this->disposed = 0;
        } else {
            $this->disposed -= $disposed;
        }
        $this->visible = true;

        return $left;
    }

    public function getAmountLeft() {
        return $this->amount - $this->disposed;
    }

    /**
     * Get disposed
     *
     * @return float 
     */
    public function getDisposed()
    {
        return $this->disposed;
    }

    /**
     * Set stockDate
     *
     * @param \DateTime $stockDate
     * @return Order
     */
    public function setStockDate($stockDate)
    {
        $this->stockDate = $stockDate;
    
        return $this;
    }

    /**
     * Get stockDate
     *
     * @return \DateTime 
     */
    public function getStockDate()
    {
        return $this->stockDate;
    }

    /**
     * Set disposed
     *
     * @param float $disposed
     * @return Order
     */
    public function setDisposed($disposed)
    {
        $this->disposed = $disposed;
    
        return $this;
    }

    public function getStatusLabel()
    {
        $label = $this->status;
        
        return $label;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function setStockDateOnStatus()
    {
        if(is_null($this->getStockDate()) && ($this->getStatus() == 'stock'))
        {
            $this->setStockDate(new \DateTime('today'));
        }
    }

    /**
     * Get amount in uCi
     *
     * @return float
     */
    public function getAmountUci()
    {
        return $this->amount / 37000;
    }

    /**
     * Set amount in uCi
     *
     * @param float $amount
     * @return Order
     */
    public function setAmountUci($amount)
    {
        $this->amount = $amount * 37000;
    
        return $this;
    }
}

src/Isotope/Bundle/DbBundle/Controller/PdfController.php
<?php
/**
 * Created by PhpStorm.
 * User: maxloyko
 * Date: 1/8/14
 * Time: 3:12 PM
 */

namespace Isotope\Bundle\DbBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

class PdfController extends Controller
{

    public function pdfAction($id)
    {
        $internal_disposal = $this->getDoctrine()->getRepository('IsotopeDbBundle:InternalDisposal')->find($id);
        if (!$internal_disposal) {
            throw $this->createNotFoundException('The Internal Disposal does not exist');
        }

        $usr= $this->get('security.context')->getToken()->getUser();

        $html = $this->renderView('IsotopeDbBundle:Pdf:internal_disposal.html.twig', array(
            'internal_disposal'  => $internal_disposal,
            'user' => $usr
        ));

        return new Response(
            $this->get('knp_snappy.pdf')->getOutputFromHtml($html),
            200,
            array(
                'Content-Type'          => 'application/pdf',
            )
        );
    }
} 

src/Isotope/Bundle/DbBundle/Resources/views/Pdf/internal_disposal.html.twig
<!DOCTYPE html>
<html {% block html_attributes %}class="no-js"{% endblock %}>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        {% block stylesheets %}{% endblock %}
        <title>title</title>
        <style>
            
            .xx_large, .x_large, .large{
                font-family: arial, verdana;
            }
            .bold{
                font-weight: bold;
            }
            .xx_large{
                font-size: 23pt;
            }
            .indent{
                height: 50px;
            }
            .x_large{
                font-size: x-large;
            }
            .large{
                font-size: large;
            }
            table{
                width: 1024px;
            }
        </style>
    </head>
    <body>
        {% block list_table %}
        <table>
            <tr class="bold xx_large">
                <td>Tonne:</td>
                <td>{{ internal_disposal.barrelCategory }}#{{ internal_disposal.barrelNumber }}</td>
            </tr>
            <tr class="bold xx_large">
                <td>Nuklid (Isotop):</td>
                <td>{{ internal_disposal.category }}</td>
            </tr>
            <tr class="bold xx_large">
                <td>Datum der Einlagerung:</td>
                <td>{{ internal_disposal.date|date("d M Y") }}</td>
            </tr>
            <tr class="bold xx_large">
                <td>Art des Abfalls:</td>
                <td>{{ internal_disposal.barrelCategory.description }}</td>
            </tr>
            <tr class="xx_large">
                <td>Berechnetes Freigabedatum am:</td>
                <td>{{ internal_disposal.getCalculatedDisposalDate|date("d M Y") }}</td>
            </tr>
            <tr class="xx_large">
                <td>Tatsächlich Freigegeben am:</td>
                <td>{%if internal_disposal.actualDisposal is not empty %}
                        {{ internal_disposal.actualDisposal|date("d M Y") }}
                    {% else %}
                    -
                    {% endif %}
                </td>
            </tr>
            <tr class="xx_large">
                <td>Name und Unterschrift:</td>
                <td>{{ user.getFullName }}</td>
            </tr>
            <tr class="indent">
                <td></td>
                <td></td>
            </tr>
            <tr class="x_large">
                <td>Beginn der Befüllung:</td>
                <td>{{ internal_disposal.fillingStart|date("d M Y") }}</td>
            </tr>
            <tr class="x_large">
                <td>Ende der Befüllung:</td>
                <td>{{ internal_disposal.fillingEnd|date("d M Y") }}</td>
            </tr>
            <tr class="x_large bold">
                <td>Ausgangsaktivität in μCi:</td>
                <td>{{ internal_disposal.amountUci | german_number_format() }}</td>
            </tr>
            <tr class="x_large">
                <td>Taragewicht der Tonne in Kg:</td>
                <td>{{ internal_disposal.barrelPackageWeight | german_number_format() }}</td>
            </tr>
            <tr class="x_large">
                <td>Tatsächliges Gewicht in Kg:</td>
                <td>{{ internal_disposal.totalWeight | german_number_format() }}</td>
            </tr>
            <tr class="x_large">
                <td>Berechnetes Gewicht des Abfalls in Gramm:</td>
                <td>{{ internal_disposal.getDropWeight | german_number_format() }}</td>
            </tr>
            <tr class="x_large">
                <td>Spezifische Aktivität in Bq/g:</td>
                <td>{{ internal_disposal.getSpecActivity | science_number_format(null, true) }}</td>
            </tr>
            <tr class="x_large">
                <td>Berechnete Abklingzeit in Tagen:</td>
                <td>{{ internal_disposal.getDaysBeforeReleaseCount | german_number_format(0) }}</td>
            </tr>
            <tr class="indent">
                <td></td>
                <td></td>
            </tr>
            <tr class="x_large bold">
                <td>Berechnungsgrundlagen:</td>
                <td></td>
            </tr>
            <tr class="large">
                <td>Halbwertszeit in Tagen:</td>
                <td>{{ internal_disposal.category.halfLife | german_number_format() }}</td>
            </tr>
            <tr class="large">
                <td>Freigabegrenzwert in Bq pro Gramm:</td>
                <td>{{ internal_disposal.category.releaseLimit | german_number_format() }}</td>
            </tr>
            <tr class="large">
                <td>Berechnungsformel der Abklingzeit:</td>
                <td>t= (ln(Ausgangsaktivität/ Freigabegrenzwert)*Halbwertszeit)/ln2</td>
            </tr>
        </table>

        {% endblock %}

    </body>
</html>

src/Isotope/Bundle/DbBundle/Resources/views/Pdf/sendBalanceReport.html.twig
<!DOCTYPE html>
<html {% block html_attributes %}class="no-js"{% endblock %}>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{{ title }}</title>
    <style>
        .adresses{
            display: block;
            width: 100%;
            min-height: 155px;
            vertical-align: top;
            margin-top: 10px;
        }
        .address{
            display: inline-block;
            width: 600px;
            vertical-align: top;
        }
        .mpizAddres{
            display: inline-block;
            width: 285px;
            margin-right: -4px;
            margin-left: 5px;
            margin-top: 50px;
            vertical-align:bottom;
        }
        .subject{
            margin-top: 140px;
            margin-bottom: 70px;
        }
        .date{
            margin-top: 40px;
            margin-left: 615px;
        }
        .content{
            margin-bottom: 30px;
        }
        table {
            width:900px;
        }
        .report{
            margin-bottom: 100px;
        }
        .report td{
            padding: 0 5px 0 5px;
        }
        .report .balance_category{
            text-align: left;
            width: 20%
        }
        .report .balance_amount, .report .balance_order_date{
            padding-right: 80px;
            text-align: right;
            width: 40%
        }

        body {
            font-size: 17pt;
            width: 900px;
        }
        .main{
           height: 1150px;
           margin:0 auto;
           width: 100%;
        }
    </style>
</head>
<body>
<div class="main">
{% block content %}
    <div class="header">
        <img src="{{ path_to_image('report_logo.png') }} " width="900" height="200">
    </div>
    {%if settings is defined %}
        <div class="adresses">
            {%if settings.address is defined %}
            <div class="address">{{ settings.address|nl2br }}</div>
            {% endif %}
            {%if settings.mpizAddres is defined %}
            <div class="mpizAddres">{{ settings.mpizAddres|nl2br }}</div>
            {% endif %}
        </div>
        {%if date is defined %}
        <div class="date">{{ date|date('d.m.Y') }}</div>
        {% endif %}
        {%if settings.subject is defined %}
        <div class="subject">{{ settings.subject|nl2br }}</div>
        {% endif %}
        {%if settings.content is defined %}
        <div class="content">{{ settings.content|nl2br }}</div>
        {% endif %}
    {% endif %}
{% endblock %}
</div>

<p>Gesamtsummen:</p>
{% block list_table %}
    <table class="report">
        <tr>
            <td class="balance_category">Isotop</td>
            <td class="balance_amount">Erwerb µCi</td>
            <td class="balance_amount">Abgabe µCi</td>
        </tr>
        {%if reports is defined %}
        {% for report in reports %}
        <tr>
            <td class="balance_category">{{ report.category }}</td>
            <td class="balance_amount">{{ report.purchased_ci | number_format('0', ',', '.')}}</td>
            <td class="balance_amount">{{ report.disposed_ci | number_format('0', ',', '.') }}</td>
        </tr>
        {% endfor %}
        {% endif %}

    </table>

    <p>Einzelaufstellung Erwerb:</p>
    <table class="report">
        <tr>
            <td class="balance_category">Isotop</td>
            <td class="balance_order_date">Bestelldatum</td>
            <td class="balance_amount">Menge µCi</td>
        </tr>
        {% if logs is defined %}
            {% for log in logs %}
                <tr>
                    <td class="balance_category">{{ log.category }}</td>
                    <td class="balance_order_date">{{ log.date|date("d.m.Y") }}</td>
                    <td class="balance_amount">{{ (log.amount / 37000) | number_format('0', ',', '.') }}</td>
                </tr>
            {% endfor %}
        {% endif %}
        </tr>
    </table>
{% endblock %}

</body>
</html>

src/Isotope/Bundle/DbBundle/Resources/views/Pdf/sendBalanceReportFooter.html.twig
<!DOCTYPE html>
<html {% block html_attributes %}class="no-js"{% endblock %}>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
        .footer{
            height: 100px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="footer">
    {% block footer %}
        <table style="width: 100%">
          <tr>
            <td style="text-align:center">
              <img class="footer_img" src="{{ path_to_image('report_footer.png') }}" width="96" height="80">
            </td>
          </tr>
        </table>
    {% endblock %}
    </div>
</body>
</html>

src/Isotope/Bundle/DbBundle/Resources/views/Pdf/sendMonthlyReport.html.twig
<table border="1">
    <tr>
        <td>Category</td>
        <td>Initial Inventory</td>
        <td>Purchased</td>
        <td>Disposed of</td>
        <td>Difference</td>
        <td>End-stock</td>
    </tr>
    {% for report in reports %}
    <tr>
        <td>{{ report.category }}</td>
        <td>{{ report.initial_stock | number_format('0', ',', '') }}</td>
        <td>{{ report.purchased | number_format('0', ',', '') }}</td>
        <td>{{ report.disposed | number_format('0', ',', '') }}</td>
        <td>{{ report.difference | number_format('0', ',', '') }}</td>
        <td>{{ report.end_stock | number_format('0', ',', '') }}</td>
    </tr>
    {% endfor %}
    </tr>
</table>